#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "Running script: pyinitor <python_version> <project_path>"
    exit 1
fi

PY_VERSION="$1"
PROJECT_PATH="$2"

# Creates project
mkdir -p "$PROJECT_PATH"
cd "$PROJECT_PATH" || exit 1

# creates virtualenv
virtualenv -p python$PY_VERSION venv

# Files in project
echo "# Environment variables" > .env
echo "# $(basename "$PROJECT_PATH")" > README.md

cat > .gitignore <<EOL
__pycache__/
*.pyc
venv/
.env
.DS_Store
EOL

cat > .dockerignore <<EOL
__pycache__/
*.pyc
venv/
.env
.DS_Store
EOL

touch requirements.txt

cat > main.py <<EOL
def main():
    print("Hello, world!")


if __name__ == "__main__":
    main()
EOL

echo "✅ Python project is created $PROJECT_PATH"

cd "$PROJECT_PATH"

# opening in vscode
code .
